In [3]:
print("Hello world")

Hello world

Key data structures
1. Series (1 Dimensional)
2. DataFrame (2 Dimensional)

In [ ]:
import pandas as pd

In [8]:

s = pd.Series([1,2,3,4,5], index=['a','b','c','d','e'])

In [9]:
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [10]:
df = pd.DataFrame({"names": ["Patu","Rohan","Harry"], "marks":[100,98,95]})

In [11]:
df

   names  marks
0   Patu    100
1  Rohan     98
2  Harry     95

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   names   3 non-null      str
 1   marks   3 non-null      int64
dtypes: int64(1), str(1)
memory usage: 180.0 bytes

Data Selection

In [14]:
df.iloc[0]

names    Patu
marks     100
Name: 0, dtype: object

In [15]:
df.head()

   names  marks
0   Patu    100
1  Rohan     98
2  Harry     95

In [20]:
df.rename(columns={"names":"nm"}, inplace=True)
# inplace = True; It modifies your main file, be careful while using it.

In [21]:
df

      nm  marks
0   Patu    100
1  Rohan     98
2  Harry     95

In [24]:
df['nm'] = df['nm'].astype(str)

In [25]:
df

      nm  marks
0   Patu    100
1  Rohan     98
2  Harry     95

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   nm      3 non-null      str
 1   marks   3 non-null      int64
dtypes: int64(1), str(1)
memory usage: 180.0 bytes

In [27]:
len(df)

3

In [29]:
df["Grades"] = [0 for i in range(len(df))]

In [30]:
df

      nm  marks  Grades
0   Patu    100       0
1  Rohan     98       0
2  Harry     95       0

In [31]:
def fx(a):
    return a*a
df["Grades + 1"] = df["Grades"].apply(fx)

In [32]:
df

      nm  marks  Grades  Grades + 1
0   Patu    100       0           0
1  Rohan     98       0           0
2  Harry     95       0           0

In [38]:
df1 = pd.DataFrame({
    "names": ["Patu","Rutu","Shiv", "Shourya","Samu"],
    "marks": [100,90,94,98,95],
})

In [39]:
df1

     names  marks
0     Patu    100
1     Rutu     90
2     Shiv     94
3  Shourya     98
4     Samu     95

In [40]:
df2 = pd.DataFrame({
    "names": ["Akash","Kim","Kai", "Mu","Sam"],
    "marks": [80,94,90,98,95],
})

In [41]:
pd.concat([df1, df2])

     names  marks
0     Patu    100
1     Rutu     90
2     Shiv     94
3  Shourya     98
4     Samu     95
0    Akash     80
1      Kim     94
2      Kai     90
3       Mu     98
4      Sam     95

In [42]:
df1 = pd.DataFrame({"name": ["Akash","Rohini"], "marks":[100,80]})

In [43]:
df2 = pd.DataFrame({"name": ["Akash","Rohini"], "Roll No":[101,102]})

In [44]:
pd.merge(df1,df2, on="name")

     name  marks  Roll No
0   Akash    100      101
1  Rohini     80      102